spring:
  application:
    name: deals

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${POSTGRES_DB:dealsdb}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:youcode2023}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081